# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Ganti dengan satu nama pengguna kamal_avatar
lamaopen_collective: # Ganti dengan satu nama pengguna Open Collectivewifisppadang
ko_fi: # Ganti dengan satu nama pengguna Ko-fiavatarbuss
tidelift: # Ganti dengan satu nama platform / nama paket Tidelift misalnya, npm / babel
community_bridge: # Ganti dengan satu nama proyek Community Bridge misalnya, cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
kustom: # Ganti hingga 4 URL sponsor kustom misalnya, ['link1', 'link2']
</s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> </s> orang </s>
